debug: false

bridge_egg:
  enabled: true
  # 保留空即不判断名字，不要带颜色符号。
  name: "搭桥蛋"
  # 1为BWIA原版样式
  # 2为类花雨庭样式，是AIGC，有缺漏(比如斜扔的最后几个方块)
  mode: 2
  max_blocks: 50

explosion_proof:
  enabled: true

fireball:
  enabled: true
  yield: 0.5
  velocity: 7.0
  damage: 4.0

tnt:
  enabled: true
  yield: 3
  fuse_ticks: 80
  damage: 3.0

# 生成点数量
res_spawner:
  zombies: 2
  pigzombies: 1

spawner:
  silverfish: true
  skeleton: true
  spider: true
  wolf: true
  task:
    teleport_owner_interval: 20
    target_enemy_interval: 200
    max_distance_teleport: 20.0

tutorial_book:
  enabled: true